import type { Metadata } from "next";
import Image from "next/image";
import { Afacad, Raleway, Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";
import Navbar from "./components/Navbar";

const afacad = Afacad({
  variable: "--font-afacad",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NederLees",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>

        {children}

        {/* Footer */}
        <footer className="light-green-bg footer">
          <div className="container">
            <div className="row">
              <div className="col-8 p-1 name-home afacad-font">
                <Image src="logo.svg" alt="NederLees Logo" width="50" height="50" />
                NederLees
              </div>
              <div className="col-4 text-center raleway-font p-3 footer-text">
                <div>
                  <a className="mail-to" href="mailto:info@nederlees.nl">
                    Email: info@nederlees.nl
                  </a>
                </div>
                <div className="mail-to">
                  Copyright © 2026 NederLees - All Rights Reserved.
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
